### ISSUE TITLE
Warbirds mk1 inline cockpit hatches

### ISSUE THREAD

**Issue by WonkierM** [FirstPersonKSP/FreeIva#438] opened 2024-09-02 21:10 UTC
Just trying out freeIva with the warbirds mk1 inline cockpit IVAs (SI and non SI), which I think are supported, it looks like they do not have rear or front hatches and so you cannot traverse to e.g. a crew cabin. Using a KSA IVA on the other hand works fine, switching with reviva.

I took a look through the configs but wasn't quite sure how it was supposed to work - I see the generic mk1 inline cockpit model is supported (which the warbirds cockpit use?) but then I don't really know what I'm doing so :)

This is with a bunch of mods installed, including reviva, rpm, aset pods etc, but I couldn't find a conflict (I might be missing something).

**Comment by JonnyOThan** [comment] 2024-09-22 15:05
dupe of #268

**Closed by JonnyOThan** 2024-09-22 15:05 UTC
Labels: duplicate, Mod Support
