### ISSUE TITLE
Mark IV Spaceplane System support 

### ISSUE THREAD

**Issue by pauverblom** [FirstPersonKSP/FreeIva#456] opened 2024-11-19 16:05 UTC
Support for the two capsules: https://forum.kerbalspaceprogram.com/topic/91713-112x-mark-iv-spaceplane-system-august-18-2024/

**Comment by JonnyOThan** [comment] 2024-11-23 01:31
This already exists.  dupe of #82

**Closed by JonnyOThan** 2024-11-23 01:31 UTC

**Comment by pauverblom** [comment] 2024-11-23 10:49
whoopsie
